### PR TITLE
Implement MediaStreamAudioSourceNode (using getUserMedia, example included)

### PR DESCRIPTION
**Pull request by jarlg**
See #3 for more details. This is a proposal to how one might connect Elm and live microphone input. The implementation depends on [elm-usermedia](https://github.com/giraj/elm-usermedia), a wrapper around `getUserMedia`.

### CODE REVIEW

**Comment by bmatcuk** [comment]
Most of your changes look good to me. I wanted to test it, but I stupidly upgraded to elm 0.15.1 which hates everything about my documentation, despite the fact that my documentation seems to follow the style guide. It refuses to build because it hates my documentation, which is pretty much the most ridiculous thing I've ever seen. After wasting a couple hours trying to figure out why it's angry about my documentation, I give up for the night. I've posted to the elm discussion group to see if anyone can tell me why it hates me so I can try again later.

Aaaaanyway, the only thing I have issue with is that you added elm-html as a dependency. That doesn't make sense because the library doesn't depend on elm-html - only your new example does. I think the solution is to have another elm-package.json file in the examples directory that lists dependencies for the examples and update the makefile to build a little differently. Can probably use the `source-directories` option in the elm-package.json to include WebAudio locally. Something like that...

In any case, I think that's probably something I can fix on my own. As soon as someone can tell me why it hates my documentation so I can give everything a quick test, I'll merge in your pull request and see what I can do about making the examples build with their own elm-package.json.

Thanks for contributing!

**Comment by jarlg** [comment]
@bmatcuk Yes, elm-html should not be a dependency, I'm just not familliar enough with Elm to make a working example without it, so I included it. Locally I've had an elm-package.json for the examples/ directory, think that should work.

Sorry you've lost time on useless stuff, can't you downgrade to 0.15? Unfortunately I don't know anything about the problems you're having..

**Comment by bmatcuk** [comment]
Looks like my documentation issue is a bug: https://github.com/elm-lang/elm-compiler/issues/993

I guess I'm going to have to downgrade to 0.15 until that gets fixed. I'll give this a try over the weekend.

**Comment by bmatcuk** [comment]
I had some time to kill at work, so I downgraded to 0.15 and tried to compile your example, but I get the following error:

```
Type mismatch between the following types on line 14, column 62 to 68:

        UserMedia.MediaStream

        { b |   label : a }

    Looks like a record is missing the field 'label'.
    Maybe there is a misspelling in a record access or record update?
    It is related to the following expression:

        stream
```

I think it's because MediaStream doesn't define a label field?

**Comment by jarlg** [comment]
Okay! I've just made that change because it makes sense, but I've never had that error myself. Strange that the compiler doesn't complain to me!

I guess if you add giraj/elm-usermedia@d93fc05817b40953ef60cc1a1709868ae9eb3da9 it should work, but I'm still not entirely sure if f.ex. `active : Signal Bool` is correct. Thank you for testing out!

**Comment by bmatcuk** [comment]
Ok, it builds now but doesn't seem to do anything... it just says "Nothing" when the page loads. Are you still working on elm-usermedia?

**Comment by jarlg** [comment]
Oh, very strange! It prompts me for access to microphone, and if I accept it will correctly handle the `Just stream -> ...` case in the view, thus creating a node for the microphone stream and immediately feeding it back to you.

I'm still quite new to Elm, what do you think might be the cause for the differences we're experiencing? Are you getting any errors in the javascript console?

Again, thanks!

**Comment by bmatcuk** [comment]
Hmm, no errors... what browser are you using? I wonder if it's some sort of security thing where it won't work if I'm loading the file locally for some weird reason. I'll see if I can figure it out on my end.

**Comment by bmatcuk** [comment]
Ok, the example works. Apparently Chrome (and most other browsers) have a security setting where they will silently fail to acquire things like the microphone if you open a file locally (via `file:///path/to/whatever`). Once I ran the example on a webserver, it worked fine. I'll merge your pull request soon =)

Thanks!

**Comment by bmatcuk** [comment]
Merged! Plus I've made a couple tweaks:
- I've removed the dependency on elm-html as discussed above.
- I've added a `elm-package.json` in the examples directory that includes elm-html as a dependency and reworked the `Makefile` to build using that.
- I've included elm-usermedia as a submodule for the time being, since elm doesn't support git dependencies and elm-usermedia isn't in the package repository.

I think I might need to declare UserMedia as an exposed module in my main `elm-package.json` since I'm including your code as a submodule? Not sure...

**Pull request merged**
